T33110 fix shadow dom fouc
endlessm/kolibri-zim-plugin pull request #14
Opened 2022-02-08 02:17 UTC by dylanmccall

https://phabricator.endlessm.com/T33110

2022-02-08 18:13 UTC, dylanmccall commented
So this _almost_ works. The current implementation puts the new DOM tree a separate container, waits for it to load, then copies it to the main (visible) container. It only almost works, because there is still a flash when styles are newly reloaded (from cache) in their new context - but it is shorter, at least. Instead, we need to do split this into some more manageable components, so we can have a component that renders a DOM tree (_not_ a URL) instead of mutating `ZimContentView`. With things split up more elegantly and connecting through props instead of internal state, we can hopefully change `ZimContentView` to use the [transitions](https://v2.vuejs.org/v2/guide/transitions.html) system we already have in Vue.

2022-02-10 05:43 UTC, dylanmccall commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> +  }
This was all copied and pasted from `zimContentView`. It makes sense that this one is the scrolling container, but some other style rules should probably only be there (and vice versa).

2022-02-10 13:04 UTC, danigm requested changes

2022-02-10 13:04 UTC, danigm commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> +        type: Element,
I'm getting some errors in the console related to this property type:

```
Invalid prop: type check failed for prop "document". Expected Element, got HTMLDocument 
```

2022-02-10 13:04 UTC, danigm commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> +          if (this.resourcesToLoad === 0 && this.resourcesLoaded === 0) {
nitpick: The second check in this `if` is not needed, I think it's enough to check the number of `resourcesToLoad`;

2022-02-10 13:04 UTC, danigm commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +    :class="[ 'content', documentReady === false ? 'content--loading' : null ]"
This can be done with a [different syntax](https://v2.vuejs.org/v2/guide/class-and-style.html#Object-Syntax):

```
class="content"
:class="{ 'content--loading': !documentReady }"
```

2022-02-10 13:04 UTC, danigm commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +    transition: opacity 0.5s ease;
This transition should be removed, it shows the unstyled content to new content transition as a fade-out & fade-in, without the transtion works correctly for me in chromium, but with this line I can see the unstyled content before the correct presentation.

2022-02-14 17:09 UTC, dylanmccall commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +    :class="[ 'content', documentReady === false ? 'content--loading' : null ]"
Ah, I was looking for that! Thank you :)

2022-02-14 20:37 UTC, manuq approved these changes

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/ZimRendererIndex.vue
> +    height: 100%;
:+1:

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +      checkDocumentLoadFinished() {
Nit: This method is not only doing the check but also doing the replacement. So I would rename it.

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +  .content--loading {
Nit why 2 dashes in this class name? We don't have other cases in our source code.

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/views.py
> +        return JsonResponse({"zimFile": zim_filename, "zimPath": random_article_path})
How is this JSON API related to the flashing of unstyled content? It seems like a fix more related to the other ticket https://github.com/endlessm/kolibri-zim-plugin/pull/15

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> +        type: Document,
:+1:

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> -    overflow: auto;
:+1:

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/DOMTreeRenderer.vue
> -  }
This is undoing a change done in this very PR. So it deserves squashing with the previous commit.

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/views.py
> +            return HttpResponseRedirect(article_url)
:+1:

2022-02-14 20:37 UTC, manuq commented on kolibri_zim_plugin/assets/src/views/ZimContentView.vue
> +        this.$emit('articleLoading');
:+1:

2022-02-14 20:37 UTC, merged